############# english navigation ##############

# Dropdown menu

[[main]]
name = "Home"
URL = "homepage/full-right/"
weight = 1

[[main]]
  name = "About Me"
  url = "about-me/"
  weight = 2

[[main]]
name = "Contact"
URL = "contact/"
weight = 3

# Dropdown menu
[[main]]
weight = 4
name = "Pages"
hasChildren = true

  [[main]]
  parent = "Pages"
  name = "Author"
  url = "author/"
  weight = 1

  [[main]]
  parent = "Pages"
  name = "Category"
  url = "categories/creativity/"
  weight = 2

  [[main]]
  parent = "Pages"
  name = "Tags"
  url = "tags/food/"
  weight = 3

  [[main]]
  parent = "Pages"
  name = "404 Page"
  url = "404/"
  weight = 4


# footer menu
[[footer]]
name = "Privacy Policy"
URL = "privacy-policy/"
weight = 1

[[footer]]
name = "Terms Conditions"
URL = "terms-conditions/"
weight = 2